.\" t
.\" @(#)mlvwm.1
'\"macro stdmacro
.de EX          \"Begin example
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.ta .3i .6i .9i 1.2i 1.5i 1.8i
.nr X
.TH mlvwm 1 "11 Feb 1997"
.SH NAME
mlvwm \- Macintosh Like Virtual Window Manager
.SH SYNOPSIS
\f4mlvwm [ \fIoptions\fP ]

.SH DESCRIPTION
.I mlvwm
is a window manager for X11 designed to look and feel like
the Macintosh<tm> environment.  It provides multiple desktops, separate
menu bars for different applications, and the ability to interact with
applications from that menu bar.  It does this by sending key sequences
to the application, such as ctrl-X or alt-Y.

.SH OPTIONS
These are the command line options that are recognized by \fImlvwm\fP:
.IP "\fB-f\fP \fIconfig_file\fP"
Causes \fImlvwm\fP to use \fIconfig_fule\fP as it's configuration file.
.IP "\fB-d\fP \fIdisplay_name\fP"
Brings \fImlvwm\fP on display \fIdisplay_name\fP instead of the name
taken from the DISPLAY environment variable.
.IP "\fB-c\fP\t"
Compatible mode.  When windows are moved or resized, the border displayed
is a dotted line instead of solid.  This causes a slight speed decline.
.IP "\fB-debug\fP"
Debug mode.  Displays debugging information.

.SH CONFIGURATION FILES
The configuration file is used to describe shortcut key bindings, menus, 
fonts, and various other settings.  It is typically ".mlvwmrc" in your
home directory, and if that does not exist it falls back to the system
default.  A different config file can be defined using the -f option
shown above.

Lines beginning with '#' are ignored by \fImlvwm\fP.

.SH BUILT IN FUNCTIONS
There are a number of built in functions in \fImlvwm\fP that may be
used in the configuration file.  If there is an error in the config file,
\fImlvwm\fP will try it's best to go on.  If it can't find a particular
icon, it will complain on startup and leave the space blank where the
icon was meant to go.  Likewise, if you have a command misspelled or something
to that effect, it will simply put up an error message and continue on
through the rest of the config file.

The following commands can be used in menus, keyboard short cuts,
and anything else along those lines:

.IP "Exec \fBapp_name\fP \fBcommand\fP"
Executes an external command as stated by \fBcommand\fP.  \fBapp_name\fP
should be set to whatever the name of the application is that will be
executed.
.IP "Nop\t"
Does nothing.
.IP "Refresh"
Refreshes the screen.
.IP "Restart [\fBwindow_manager\fP]"
Restarts \fImlvwm\fP or, if \fBwindow_mananger\fP is defined, restart into
that window manager.
.IP "Exit\t"
Quits \fImlvwm\fP.
.IP "Desk [\fB+\fP|\fB-\fP|\fBnumber\fP]"
Changes desktops to \fBnumber\fP or, if + or - is the argument, goes up
one or down one desktop, respectively.
.IP "NextWindow"
Switches to the next active window.  Windows that are hidden or defined
in SkipSelect are not chosen.  This includes windows in other desktops
in it's list of windows to choose from.
.IP "PreviousWindow"
Swtiches to the previous active window.  Windows that are hidden or defined
in SkipSelect are not chosen.  This includes windows in other desktops
in it's list of windows to choose from.
.IP "NextSameDeskWindow"
Switches to the next active window.  Windows that are hidden or defined
in SkipSelect are not chosen.  Windows in other desktops are not chosen.
.IP "PreviousSameDeskWindow"
Switches to the previous active window.  Windows that are hidden or defined
in SkipSelect are not chosen.  Windows in other desktops are not chosen.
.IP "ShadedUnShadeActive"
Shades or UnShades active window.
.IP "HideActive"
Hides active window.
.IP "HideOthers"
Hides all other windows except the active one.
.IP "ShowAll"
All hidden windows are unhidden.
.IP "MoveWindow"
Move a window, chosen after this command is selected.
.IP "ResizeWindow"
Resize a window, chosen after this command is selected.
.IP "KillWindow"
Kills a chosen window.
.IP "SendMessage \fBsequence\fP"
A keypress is sent to the active window.  The keys pressed are defined
in a similar fashion to those in the ShortCut command.  You specify a
special key with it's corresponding capital letter identifier and a +
symbol.  For instance, if you wanted to set the sequence: Ctrl-x, you
would use C+x.

The following commands are used to change or describe \fImlvwm\fP's
functionality:

.IP "Desktopnum \fBnum\fP"
The number of desktops available.  Defaults to 1.
.IP "StickShade"
Shaded windows are present no matter what desktop you are on, instead
of staying on a particular desktop.  This is not the default behavior.
.IP "StickHide"
Hidden windows are present no matter what desktop you are on, instead
of staying on a particular desktop.  This is not the default behavior.
This means that if you hide a window in one desktop, and move to another,
then unhide it, it will appear in that desktop, instead of the desktop
it was originally in.
.IP "ShadeMap"
When a window is unhidden, shading remains.  The default is for shading
to be canceled when a window is unhidden.
.IP "DoubleClickTime \fBtime\fP"
The number of milliseconds in which you must click the mouse button twice
in order to register a double click.
.IP "FollowToMouse"
The active window is the window the mouse is currently over.  If you move
the mouse away from the current window and/or over another, you lose
focus in the current one.  This is not set up by default.
.IP "FlushMenu \fBspeed\fP \fBflashes\fP"
Determines how fast the flashes are when you choose an option from a menu,
as well as how many times it does so.
.IP "IconPath \fBpath\fP"
Specify the path \fImlvwm\fP is to search in order to find it's icons.
Separate directories should be separated with a : and listed in the order
you wish them to be searched.  This needs to be defined before any
references to icons are made.
.IP "IconMenuIcon \fBicon\fP"
This is the icon to be used with the windowlist menu on right side of the
menu bar.
.IP "MenuBarFont \fBfont\fP"
The font the menu bar is to use.
.IP "MenuFont \fBfont\fP"
The font the menus are to use.
.IP "TitleBarFont \fBfont\fP"
The font on the title bars of windows.
.IP "Read \fBfilename\fP"
Reads in a separate configuration file.
.IP "Menu \fBname\fP[, \fBoptions\fP] ... END"
Starts a menu block for the specified \fBname\fP menu.  After the name of
the menu, some options may be defined as listed below to change the behavior
of that menu.  All lines following the Menu command are read in as menu
items until an END statement is reached.  Description of menu items will
be discussed after the options.

Menu options are as follows:

Right - places the menu on the right side of the menu bar.

Left - places the menu on the left side of the menu bar.  This is default.

Icon \fBicon\fP - assigns an icon to be displayed on the menu bar instead
of a label.

Label \fBlabel\fP - assigns a label to be displayed on the menu bar instead
of an icon.

Stick - menu label is shown any time, in spite of the designation of which
application it is associated with via the MenuBar command.

NonStick - opposite of Stick.  This is default.


Menu items are described as follows:

"label" options

Multiple options are separated by commas.  Options you can choose are as
follows:

Gray - grays out a menu item.

Black - makes a menu item black.

Check - places a check mark next to item.

NonCheck - doesn't place a check mark next to item.

Select - makes a menu item selectable.

NonSelect - prevents a menu item from being selectable.

Icon \fBicon\fP - specifies an icon to place next to the menu item's label.

Action \fBcommand\fP - performs any built in \fBcommand\fP.

.IP "Swallow \fBappname\fP \fBoptions\fP"
Swallows an application into the menu bar.  \fBoptions\fP are separated
by commas.  \fBappname\fP should match the name of the application that
will be swallowed.  The following options are allowed:

Right - places the menu on the right side of the menu bar.  This is default.

Left - places the menu on the left side of the menu bar.

Action \fBcommand\fP - performs any built in \fBcommand\fP.  This is where
an Exec should be performed of the application to be swallowed.

Stick - menu label is shown any time, in spite of the designation of which
application it is associated with via the MenuBar command.  This is default.

NonStick - opposite of Stick.

.IP "MenuBar \fBappname\fP ... END"
This describes the names of the menus to be displayed, given a particular
\fBappname\fP is active.  The keyword \fBdefault\fP can be placed for
\fBappname\fP to set up a menu bar for any application that does not
have it's own specific menu bar.  Menus are listed one per line after
the MenuBar line, and closed off with an END statement.

.IP "Style ... END"
This is used to describe certain attributes of particular windows, such
as decorations, MenuBars, mini-icons, and various other attributes.
The wildcards, * and ?, can be used.  Lines are set up as follows:

"appname" \fBoptions\fP

Multiple \fBoptions\fP are separated by commas, and can be chosen from
the following:

NormalDecoration - Places standard decorations (ie all the defaults)
around a particular window.

NoSbarH - Horizontal scroll bar is removed.

NoSbarV - Vertical scroll bar is removed.

NoResizeR - no resize 'button'.  This is automatic if both NoSbarH and NoSbarV
are defined.

NoTitle - Removed title bar.

NoMinMaxR - Min/Max 'button' is removed.  Automatic when NoTitle defined.

NoCloseR - Close 'button' is removed.  Automatic when NoTitle defined.

NoWinList - Prevents window from being show on the window list.

NoFocus - Does not allow window to get focus.

StayOnTop - Window stays above all other windows on the screen.

Sticky - Window stays on screen even if you change desktops.

SkipSelect - Prevents window from getting chosen by NextWindow, PreviousWindow,
PreviousSameDeskWindow, and NextSameDeskWindow.

EnableScroll - Activates scroll bars.

MaxmizeScale - The percentage the window will increase in size when it
maximized.

MiniIcon \fBicon\fP - \fBicon\fP is used to represent that particular window.

MenuBar \fBmenubar\fP - Switches the menu bar to \fBmenubar\fP when that
application is active.

.IP "ShortCut ... END"
Binds key combinations to functions.  Short cuts are listed one per line
in the following format:

KeyName KeyboardModifier Command

After all Short cuts are listed, an END statement should be placed.
KeyboardModifier's are as follows:

.EX
S - Shift key
C - Control key
M - Mod1 key
1 - Mod1 key
2 - Mod2 key
3 - Mod3 key
4 - Mod4 key
5 - Mod5 key
A - Any Modifier
N - No Modifier
.EE

.SH FILES
.nf
$HOME/.mlvwmrc
$MLVWMLIBDIR/system.mlvwmrc
.fi

.SH COPYRIGHT NOTICES
This program is distributed as freeware. The copyright remains with
the author.

Macintosh is a registered trademark of Apple Computer, Inc.

.SH AUTHOR
Takashi HASEGAWA
.I tak@bioele.nuee.nagoya-u.ac.jp
